### ISSUE TITLE
Disable item interactions in spectator mode

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#42]
some plugin items are known to work in spectator mod(ex: QualityArmory guns)

**Comment by LazoYoung** [comment]
You can't hold any item in spectator mode. How does it work despite that?

**Comment by jupiter1390** [comment]
> You can't hold any item in spectator mode. How does it work despite that?

Hold any QualityArmory Gun item and left click it, it will work

**Comment by LazoYoung** [comment]
I took an alternative approach. Plugin will always clear inventory of dead players.
