### ISSUE TITLE
Lots of player status gets reset after game

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#51]
Potion Effect, Health, Exp, and etc options

**Comment by LazoYoung** [comment]
Be specific while you suggest your idea. I'm gonna pretend I never heard **etc**

**Comment by LazoYoung** [comment]
Implemented in 6924db0. Please review this hot potato. Report bug if you've discovered any.

**Comment by jupiter1390** [comment]
tested and approved
