### ISSUE TITLE
Check Entity existence

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#54]
1. Able to check Entitytype(mob type) and Name

2. Association with Area; if not associated with area it will check every entities in game world

3. Check entity number

**Comment by LazoYoung** [comment]
1. You can check the specific mob's type and its name using Bukkit API:
```groovy
import org.bukkit.entity.*

Mob boss = MobModule.spawnMob("ZOMBIE", "tag123").get(0)
EntityType type = boss.getType()
String name = boss.getName()
```

2. Do you mean you need a function to retrieve the entire mobs inside the boundary of area?
Sure, I can make one if my guess is right.

3. Is this related to Q.2?

**Comment by jupiter1390** [comment]
2 - yes
3- both (returning the number of entities)

**Comment by LazoYoung** [comment]
Got it. I'm working on this.
