### ISSUE TITLE
Libsdisguise support?

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#61]
Supporting disguise for kits(kit disguise disabled when changing kit), able to toggle disguiseviewself, manual disguise toggle, undisguise function

would be nice if disguiseviewself was false for default when disguise applied

**Comment by LazoYoung** [comment]
Implemented. Test and approval is required.

**Comment by jupiter1390** [comment]
tested and approved

**Comment by LazoYoung** [comment]
@jupiter1390 Please checkout PlayerModule.disguiseAsCustomPreset() as well.
Javadoc will be updated in a moment. Related commit: 240682be

**Comment by LazoYoung** [comment]
@jupiter1390 I'm gonna close this. If you find the new function malfunctioning, then re-open this thread.
