### ISSUE TITLE
Spawnpoint as area / area safespawn

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#62]
1. Spawnpoint can be set as area, spawning players/entities in random location inside area
2. Area safespawn(before spawning player/entity inside area randomly, check if the position is safe)
safe position requirements: cannot be suffocated, not in midair
safe position option can be enabled/disabled per eash spawn module(another boolean option added to spawn modules)

**Comment by LazoYoung** [comment]
1. Sure, I'll look into this.
2. I don't think it is worth checking for safe zone. Since the plugin offers you method to select area with ease and you have full control to handle it, then IMO you're responsible for the outcome.

**Comment by jupiter1390** [comment]
I think it's worth to add safezone check option because safezone checking is almost necessary in lots of spawn situations, and it's better to add it as a additional option in spawn module with rather than checking safezone manually with script every time

**Comment by LazoYoung** [comment]
Please explain what situations are those in which safe checking is necessary.
Also you missed the point; you don't need to check safezone if you have carefully selected area in the first place.

**Comment by jupiter1390** [comment]
as spawning mobs in area(currently) or spawning players in area(planned), if the area is partially filled with block or the area is more than 1 block high, there is chance that mob/player will spawn midair/inside block

Since spawning mobs/players in area is done beacuse you need to use a large zone as spawnpoint but don't want to manually capture each spawnpoint as spawn tag, I think this feature is necessary
(Only for spawning in area tag, not for spawn tag)

**Comment by LazoYoung** [comment]
Should be ready to go. Final test is required before closing this thread.

**Comment by jupiter1390** [comment]
tested and approved
