### ISSUE TITLE
worldborder render issue

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#64]
worldborder is sometimes not rendered

**Comment by LazoYoung** [comment]
I need more test and experiments

**Comment by LazoYoung** [comment]
I'm convinced that this is due to [the issue in Minecraft](https://bugs.mojang.com/browse/MC-121997) itself. Please confirm @jupiter1390

**Comment by jupiter1390** [comment]
confirmed

**Comment by LazoYoung** [comment]
I'm closing this thread as I have no chance of fixing it.
