### ISSUE TITLE
Map pointer doesn't appear in game.

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#66]
player marker won't display properly in map(made while editing game) while in minigame

**Comment by LazoYoung** [comment]
Player marker won't appear if you crafted a normal map instead of locator map.
@jupiter1390 Perhaps 'Marking points' are what you're trying to say about?

**Comment by jupiter1390** [comment]
Marking points render properly, player marker(displaying player's current location) won't display properly
It would display normally before saving and re-loading the map
