### ISSUE TITLE
Add command to modify player data files outside game.

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#72]
command can only be run at server/default OP permissions
command will not run if the targeted game is being played by targeted player
 
Expecting command structure like:
/cyml modify "game_name" "player_name" "integer_name" "value"
(player_name can be ignored when running as OP - player name value will use the player executing command instead)
/cyml remove/add "game_name" "player_name" "integer_name"

P.S. This command must be capable to be run outside game.

**Comment by LazoYoung** [comment]
CraftGames is not designed to work this way. Game resources are discarded after a game ends so it's illegal to access them from the outside.
This won't be worked on so I'm closing this thread.
