### ISSUE TITLE
Requesting Modules

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#84]
1. Module Disabling/Enabling fall damage
2. Module Disabling/Enabling hunger and health regeneration (like the world option in multiverse)
3. Module Disabling/Enabling Instant death in void

**Comment by LazoYoung** [comment]
1,3 -> #82

**Comment by LazoYoung** [comment]
2 ->
* [Player#setFoodLevel(int)](https://papermc.io/javadocs/paper/1.15/org/bukkit/entity/Player.html#setFoodLevel-int-)
* [Player#setSaturation(float)](https://papermc.io/javadocs/paper/1.15/org/bukkit/entity/Player.html#setSaturation-float-)
* [Player#setHealth(double)](https://papermc.io/javadocs/paper/1.15/org/bukkit/entity/Damageable.html#setHealth-double-)
