### ISSUE TITLE
Enhanced inventory-lock feature.

### ISSUE THREAD

**Issue by jupiter1390** [LazoYoung/CraftGames#85]
https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/b/b2/Items_slot_number.png/300px-Items_slot_number.png?version=4819ee83ebf47118c5831067141e7ec7

Additional data input to lock specific slots(in ranged value)?

**Comment by jupiter1390** [comment]
addtion: if the locked slot is player's hotbar, item will not be dropped  either by Q or dragging out of inventory

**Comment by LazoYoung** [comment]
So basically you wanna keep the items in locked slots, allowing random item to fill an empty locked slot in the meantime. Correct?

**Comment by jupiter1390** [comment]
item can be still placed in empty locked slot, but they will not be removed from inventory / moved to other slot

**Comment by LazoYoung** [comment]
결론적으로 잠궈진 아이템 슬롯은
1) 비어 있다면, 채워지는 것이 가능하다.
2) 채워져 있다면, 다른 슬롯으로 옮기거나 인벤토리 바깥으로 빼낼 수 없다.
