### ISSUE TITLE
MythicMobs spamming console

### ISSUE THREAD

**Issue by MattGold-5829** [LazoYoung/CraftGames#93]
We can't figure out what does it but mythic mobs spams the console with

[09:37:30 ERROR]: [MythicMobs] [SCHEDULER] Exception thrown whilst executing task
[09:37:30 WARN]: java.lang.NullPointerException

**Comment by LazoYoung** [comment]
Sir you're asking me why MythicMobs plugin is spamming that error but it seems to have nothing to do with my plugin. Otherwise you might have to submit your game script and the installed version of CraftGames as well in order for me to see the picture to seek the problem.

**Comment by LazoYoung** [comment]
I'm closing this thread as I got no reply for weeks. If you need further assist, you may open up another issue.
